name: Databricks CD with AAD Token

on:
  pull_request:
    types: [completed]
  push:
    paths:
      - "action.yml"
      - ".github/workflows/cd-aad.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
                    
      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0    
      
      - id: adb-login
        uses: Azure/azure-resource-login-action@v1.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-url: AadGraph
      
      - id: access-key
        name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/sample1.sh
            $GITHUB_WORKSPACE/sample1.sh
            
      - name: set-databricks-token
        run: | 
          echo "DATABRICKS_TOKEN= ${{ steps.adb-login.output.token }}" >> $GITHUB_ENV
          
      - name: Import Databricks notebooks
        uses: ./
        with:
          databricks-host: "https://adb-2700622637314445.5.azuredatabricks.net"
          databricks-token: ${{ steps.adb-login.output.token }}
          local-path: ./notebooks
          remote-path: /import-notebook
