name: Databricks CD with AAD Token

on:
  pull_request:
    types: [completed]
  push:
    paths:
      - "action.yml"
      - ".github/workflows/cd-aad.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
          
      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0
        
      - id: azure-resource-login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      
      
      - name: set-databricks-token
        run: | 
          token=$(az account get-access-token --resource=c8807a23-7b1c-42ac-9c48-99686f967189 --query accessToken --output json)
          echo "DATABRICKS_TOKEN= $token" >> $GITHUB_ENV
            
      - name: Import Databricks notebooks
        uses: ./
        with:
          databricks-host: "https://adb-2700622637314445.5.azuredatabricks.net"
          databricks-token: ${{ env.DATABRICKS_TOKEN }}
          local-path: ./notebooks
          remote-path: /import-notebook
