name: Databricks CD with AAD Token

on:
  pull_request: 
    types: [closed]
  push:
    paths:
      - "action.yml"
      - ".github/workflows/cd-aad.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: schdck/create-env-json@v1
        id: create-env
        with:
            file-name: 'env.json'
            client-id: "8894b97f-acff-4637-a536-c0293b6ab3f4"
            tenant-id: "f5222e6c-5fc6-48eb-8f03-73db18203b63"
            subscription-id: "6f30d7aa-39a2-44ca-ab61-c9ba500fe1fb"
            
      - uses: actions/checkout@v2 
          
      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0
        
      - id: azure-resource-login
        uses: Azure/azure-resource-login-action@v1.0.0
        with:
          creds: ${{ steps.create-env.outputs.full-path }}
          resource-url: 6f30d7aa-39a2-44ca-ab61-c9ba500fe1fb
      
      - name: set-databricks-token
        run: | 
          echo "DATABRICKS_TOKEN= ${{ steps.azure-resource-login.outputs.token }}" >> $GITHUB_ENV
            
      - name: Import Databricks notebooks
        uses: ./
        with:
          databricks-host: ${{ secrets.ADB_HOST }}
          databricks-token: ${{ env.DATABRICKS_TOKEN }}
          local-path: ./notebooks
          remote-path: /import-notebook
