name: Databricks CD

on: 
  pull_request:
    types: [closed]
  push:
    branches:
      - master
    paths:
      - "action.yml"
      - "./github/workflows/cd.yml"
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    
    steps:
    
      - uses: actions/checkout@v2
      
      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0
        
      - id: azure-resource-login
        name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: Azure/azure-resource-login-action@v1.0.0
        with:
            client-id: "8894b97f-acff-4637-a536-c0293b6ab3f4"
            tenant-id: "f5222e6c-5fc6-48eb-8f03-73db18203b63"
            subscription-id: "6f30d7aa-39a2-44ca-ab61-c9ba500fe1fb"
            enable-AzPSSession: true
      
      
      - name: set-databricks-token
        run: | 
          echo "DATABRICKS_TOKEN= ${{ steps.azure-resource-login.outputs.token }}" >> $GITHUB_ENV
            
      - name: Import Databricks Notebooks
        uses: ./
        with:
          databricks-host: "https://adb-2700622637314445.5.azuredatabricks.net"
          databricks-token: ${{ env.DATABRICKS_TOKEN }}
          local-path: ./notebooks
          remote-path: /import-notebook
