on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: schdck/create-env-json@v1
        id: create-env
        with:
            file-name: 'env.json'
            clientId: 8894b97f-acff-4637-a536-c0293b6ab3f4
            clientSecret: Ga07Q~YIPC2DxGn1IYWko1lR_7Z4JGjhx7DRE
            tenantId: f5222e6c-5fc6-48eb-8f03-73db18203b63
            subscriptionId: 6f30d7aa-39a2-44ca-ab61-c9ba500fe1fb
            
      - uses: azure/login@v1
        with:
          creds: ${{ steps.create-env.outputs }}
    
      - run: |
          az webapp list --query "[?state=='Running']"
